services:

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  dag-api:
    build: .
    environment:
      DATABASE_URL: "postgresql+asyncpg://user:password@postgres:5432/db"

    ports:
      - "8080:8080"

    depends_on:
      postgres:
        condition: service_healthy